### ISSUE TITLE
Decide on product name

### ISSUE THREAD

**Issue by slheavner** [slheavner/MorgantownUVotingSystem#4]
Discuss product names. List any in the file Stephen made, and discuss them here. 

Feel free to edit this issue description as seen fit.

Edit: Forgot to add, I can change the name of the repo when we decide.

Edit: proposed product names are [here](https://github.com/slheavner/MorgantownUVotingSystem/blob/dev/doc/ApplicatonNameBrainstorm.md)

**Comment by DewMonger** [comment]
Demophone is my personal favorite, but Delphi is definitely more catchy. So my vote is for Delphi.
